### ISSUE TITLE
HTML entities should not be captured in line noise

### ISSUE THREAD

**Issue by ggrossman** [zendesk/credit_card_sanitizer#25]
https://github.com/zendesk/credit_card_sanitizer/pull/24 added checking for the HTML entity `&#43;` to prevent redaction. However, we should not be including ANY numeric HTML entities as part of sequences recognized as credit card numbers... these will surely be false positives. One way to fix would just be to remove `;` from acceptable line noise... that is unlikely to be a credit card number separator anyway.

**Comment by ckumar1** [comment]
Fixed in #26
