### ISSUE TITLE
Not compatible with Airbrake v5

### ISSUE THREAD

**Issue by bquorning** [zendesk/credit_card_sanitizer#39]
https://github.com/airbrake/airbrake/blob/master/README.md#integration-with-filter_parameters says

> 3. If you use Procs to configure `filter_parameters`, the procs must return an Array of keys compatible with the Airbrake whitelist/blacklist option (String, Symbol, Regexp)

See also the example configuration at https://github.com/kyrylo/airbrake-ruby-issue108/blob/master/config/initializers/1_filter_parameter_logging.rb

**Comment by kintner** [comment]
cc @lisacf

**Comment by bquorning** [comment]
Hmm, perhaps it actually is compatible anyway. I’ll need to take a closer look.
